name: one_try
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  camera: ^0.10.5+4
  flutter:
    sdk: flutter
  http: ^1.1.0
  camera_windows: ^0.2.1+8
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  flutter_animated_button: ^2.0.3
  window_manager: ^0.3.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/background.png
  fonts:
    - family: rox     
      fonts:
        - asset: assets/fonts/RoxboroughCF.ttf
    - family: dm     
      fonts:
        - asset: assets/fonts/DMSansRegular.ttf    
  uses-material-design: true
